micronaut:
  micronaut:
    security:
      authentication: bearer
      token:
        jwt:
          signatures:
            secret:
              generator:
                refresh-token:
                  secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:khanimkhanim}"'
  application:
    name: micronautguide
